from binary_tree import *

bt = BinaryTree(5)
print('Удаляем корень без детей')
bt.delete(5)
print(bt)
print(bt.count)
print('------------------')
bt.add(10)
bt.add(5)
bt.add(15)
print(bt)
print(bt.count)
print('------------------')
print('Удаляем корень 5 с 2мя детьми')
bt.delete(5)
print(bt)
print(bt.count)
print('------------------')
print('Удаляем корень 10 с 1м ребенком')
bt.delete(10)
print(bt)
print('------------------')
bt.add(30)
print(bt)
print('------------------')
print('Удаляем звено 30 без детей')
bt.delete(30)
print(bt)
print('------------------')
bt.add(30)
bt.add(35)
print(bt)
print('------------------')
print('Удаляем звено 30 с 1 ребенком')
bt.delete(30)
print(bt)
print('------------------')
bt.add(20)
bt.add(60)
bt.add(40)
bt.add(45)
print(bt)
print(bt.count)
print('------------------')
print('Удаление звена 35 с 2 детьми и минимальное значение с 1 ребенком')
bt.delete(35)
print(bt)
print(bt.count)
print('------------------')
bt.delete(45)
print(bt)
print(bt.count)
print('------------------')
print('Удаление звена 40 с 2 детьми и минимальное значение без детей')
bt.delete(40)
print(bt)
print(bt.count)
