from binary_tree import *

bt = BinaryTree(5)
bt.delete(5)     # удаляем корень без детей
print(bt)
print(bt.count)
print('------------------')
bt.add(10)
bt.add(5)
bt.add(15)
print(bt)
print(bt.count)
print('------------------')
bt.delete(5)    # удаляем корень с 2мя детьми
print(bt)
print(bt.count)
print('------------------')
bt.delete(10)   # удаляем корень с 1м ребенком
print(bt)
print('------------------')
bt.add(30)
print(bt)
bt.delete(30)   # удаляем звено без детей
print('------------------')
print(bt)
print('------------------')
bt.add(30)
bt.add(35)
print(bt)
print('------------------')
bt.delete(30)   # удаляем звено с 1 ребенком
print(bt)
print('------------------')
bt.add(20)
bt.add(60)
bt.add(40)
bt.add(45)
print(bt)
print(bt.count)
print('------------------')
bt.delete(35)   # удаление звена с 2 детьми и минимальное значение с 1 ребенком
print(bt)
print(bt.count)
print('------------------')
bt.delete(45)
print(bt)
print(bt.count)
print('------------------')
bt.delete(40)   # удаление звена с 2 детьми и минимальное значение без детей
print(bt)
print(bt.count)
